using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Noggog;
using System.Threading.Tasks;
using System;
using System.Text.RegularExpressions;

namespace MaleAAGenerator
{
    public class Program
    {
        static Lazy<Settings> Settings = null!;
        public static Task<int> Main(string[] args)
        {
            return SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out Settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "MaleAAGenerator.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
             if (Settings.Value.TargetMods.Count == 0)
            {
                System.Console.WriteLine("Must at least specify one target mod in order to do anything.");
                return;
            }

            foreach (var AAGetter in state.LoadOrder.PriorityOrder.ArmorAddon().WinningOverrides())
            {            
                var AASetter = AAGetter.DeepCopy();
                if(!Settings.Value.TargetMods.Contains(AASetter.FormKey.ModKey)) continue;
                if(AASetter.WorldModel?.Female?.File is null) continue;
                if(AASetter.BodyTemplate is null) return;    

                string pattern = "_1.nif|_0.nif|.nif";         
           
                var fileOrig = Regex.Split( AASetter.WorldModel.Female.File,pattern);
                var fileNew = fileOrig[0] + Settings.Value.Suffix;
                
                if(AASetter.BodyTemplate.FirstPersonFlags.HasFlag(BipedObjectFlag.Head)
                || AASetter.BodyTemplate.FirstPersonFlags.HasFlag(BipedObjectFlag.Hair)
                || AASetter.BodyTemplate.FirstPersonFlags.HasFlag(BipedObjectFlag.Circlet)){
                    fileNew += ".nif";
                }else{
                    AASetter.WeightSliderEnabled.Male = true;
                    fileNew += "_1.nif";
                }
                
                AASetter.WorldModel.Male = AASetter.WorldModel.Female.DeepCopy();
                AASetter.WorldModel.Male.File = fileNew;
                System.Console.WriteLine($"{AASetter.EditorID}: Set Mesh To {fileNew}");
                state.PatchMod.ArmorAddons.Set(AASetter);
            }
        }
    }
}
